/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchCancelOrdersRequest : Request for cancelling a batch of orders
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchCancelOrdersRequest {
    /// An array of order IDs to cancel.
    #[serde(rename = "ids")]
    pub ids: Vec<uuid::Uuid>,
}

impl BatchCancelOrdersRequest {
    /// Request for cancelling a batch of orders
    pub fn new(ids: Vec<uuid::Uuid>) -> BatchCancelOrdersRequest {
        BatchCancelOrdersRequest {
            ids,
        }
    }
}

