/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchCreateOrdersRequest : Request for submitting a batch of orders
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchCreateOrdersRequest {
    /// An array of individual orders to place.
    #[serde(rename = "orders")]
    pub orders: Vec<models::CreateOrderRequest>,
}

impl BatchCreateOrdersRequest {
    /// Request for submitting a batch of orders
    pub fn new(orders: Vec<models::CreateOrderRequest>) -> BatchCreateOrdersRequest {
        BatchCreateOrdersRequest {
            orders,
        }
    }
}

