/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchCancelOrdersIndividualResponse : Response for cancelling a batch of orders
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchCancelOrdersIndividualResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::JsonError>>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<Box<models::Order>>,
    /// Optional order_id to identify the orders that errored.
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<uuid::Uuid>,
    /// ReducedBy is how much the count of the order was reduced by because of this operation.
    #[serde(rename = "reduced_by")]
    pub reduced_by: i32,
}

impl BatchCancelOrdersIndividualResponse {
    /// Response for cancelling a batch of orders
    pub fn new(reduced_by: i32) -> BatchCancelOrdersIndividualResponse {
        BatchCancelOrdersIndividualResponse {
            error: None,
            order: None,
            order_id: None,
            reduced_by,
        }
    }
}

