/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CancelOrderResponse : Response to an attempt to cancel an order including the order itself and its last status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelOrderResponse {
    #[serde(rename = "order")]
    pub order: Box<models::Order>,
    /// ReducedBy is how much the count of the order was reduced by because of this operation.
    #[serde(rename = "reduced_by")]
    pub reduced_by: i32,
}

impl CancelOrderResponse {
    /// Response to an attempt to cancel an order including the order itself and its last status.
    pub fn new(order: models::Order, reduced_by: i32) -> CancelOrderResponse {
        CancelOrderResponse {
            order: Box::new(order),
            reduced_by,
        }
    }
}

