/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateOrderResponse : Response for submitting an order containing the order details and the order's last status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrderResponse {
    #[serde(rename = "order")]
    pub order: Box<models::OrderConfirmation>,
}

impl CreateOrderResponse {
    /// Response for submitting an order containing the order details and the order's last status.
    pub fn new(order: models::OrderConfirmation) -> CreateOrderResponse {
        CreateOrderResponse {
            order: Box::new(order),
        }
    }
}

