/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecreaseOrderRequest {
    /// Number of contracts to decrease the order's count by. One of reduce_by or reduce_to must be provided.
    #[serde(rename = "reduce_by", skip_serializing_if = "Option::is_none")]
    pub reduce_by: Option<i32>,
    /// Number of contracts to decrease the order to.  If the orders remaining count is lower, it does nothing. One of reduce_by or reduce_to must be provided
    #[serde(rename = "reduce_to", skip_serializing_if = "Option::is_none")]
    pub reduce_to: Option<i32>,
}

impl DecreaseOrderRequest {
    pub fn new() -> DecreaseOrderRequest {
        DecreaseOrderRequest {
            reduce_by: None,
            reduce_to: None,
        }
    }
}

