/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeStatus {
    /// False if the core Kalshi exchange is no longer taking any state changes at all. This includes but is not limited to trading, new users, and transfers. True unless we are under maintenance.
    #[serde(rename = "exchange_active")]
    pub exchange_active: bool,
    /// True if we are currently permitting trading on the exchange. This is true during trading hours and false outside exchange hours. Kalshi reserves the right to pause at any time in case issues are detected.
    #[serde(rename = "trading_active")]
    pub trading_active: bool,
}

impl ExchangeStatus {
    pub fn new(exchange_active: bool, trading_active: bool) -> ExchangeStatus {
        ExchangeStatus {
            exchange_active,
            trading_active,
        }
    }
}

