/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventResponse {
    #[serde(rename = "event")]
    pub event: Box<models::EventData>,
    /// Data for the markets in this event. This field is deprecated in favour of the \"markets\" field inside the event. Which will be filled with the same value if you use the query parameter \"with_nested_markets=true\".
    #[serde(rename = "markets")]
    pub markets: Vec<models::Market>,
}

impl GetEventResponse {
    pub fn new(event: models::EventData, markets: Vec<models::Market>) -> GetEventResponse {
        GetEventResponse {
            event: Box::new(event),
            markets,
        }
    }
}

