/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetExchangeAnnouncementsResponse {
    /// A list of exchange-wide announcements.
    #[serde(rename = "announcements")]
    pub announcements: Vec<models::Announcement>,
}

impl GetExchangeAnnouncementsResponse {
    pub fn new(announcements: Vec<models::Announcement>) -> GetExchangeAnnouncementsResponse {
        GetExchangeAnnouncementsResponse {
            announcements,
        }
    }
}

