/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPortfolioSettlementsResponse {
    /// The Cursor represents a pointer to the next page of records in the pagination. Use the value returned here in the cursor query parameter for this end-point to get the next page containing limit records. An empty value of this field indicates there is no next page.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Settlement summaries for all markets the user participated in
    #[serde(rename = "settlements")]
    pub settlements: Vec<models::Settlement>,
}

impl GetPortfolioSettlementsResponse {
    pub fn new(settlements: Vec<models::Settlement>) -> GetPortfolioSettlementsResponse {
        GetPortfolioSettlementsResponse {
            cursor: None,
            settlements,
        }
    }
}

