/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMarketCandlesticksResponse {
    /// Unique identifier for the market.
    #[serde(rename = "candlesticks")]
    pub candlesticks: Vec<models::MarketCandlestick>,
    /// Unique identifier for the market.
    #[serde(rename = "ticker")]
    pub ticker: String,
}

impl GetMarketCandlesticksResponse {
    pub fn new(candlesticks: Vec<models::MarketCandlestick>, ticker: String) -> GetMarketCandlesticksResponse {
        GetMarketCandlesticksResponse {
            candlesticks,
            ticker,
        }
    }
}

