/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoginResponse : The `token` field must be passed in future requests as a header.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginResponse {
    /// Member's user ID.
    #[serde(rename = "member_id", skip_serializing_if = "Option::is_none")]
    pub member_id: Option<uuid::Uuid>,
    /// Access token for a member role session in the API.
    #[serde(rename = "token")]
    pub token: String,
}

impl LoginResponse {
    /// The `token` field must be passed in future requests as a header.
    pub fn new(token: String) -> LoginResponse {
        LoginResponse {
            member_id: None,
            token,
        }
    }
}

