/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderBook : Contains the number of pending resting order for each price on a specific market.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderBook {
    #[serde(rename = "no")]
    pub no: Vec<Vec<i32>>,
    #[serde(rename = "yes")]
    pub yes: Vec<Vec<i32>>,
}

impl OrderBook {
    /// Contains the number of pending resting order for each price on a specific market.
    pub fn new(no: Vec<Vec<i32>>, yes: Vec<Vec<i32>>) -> OrderBook {
        OrderBook {
            no,
            yes,
        }
    }
}

