/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceDistribution {
    /// Last traded YES contract price on the market during the candlestick period. May be empty if there was no trade during the period.
    #[serde(rename = "close", skip_serializing_if = "Option::is_none")]
    pub close: Option<i64>,
    /// Highest traded YES contract price on the market during the candlestick period. May be empty if there was no trade during the period.
    #[serde(rename = "high", skip_serializing_if = "Option::is_none")]
    pub high: Option<i64>,
    /// Lowest traded YES contract price on the market during the candlestick period. May be empty if there was no trade during the period.
    #[serde(rename = "low", skip_serializing_if = "Option::is_none")]
    pub low: Option<i64>,
    /// Mean traded YES contract price on the market during the candlestick period. May be empty if there was no trade during the period.
    #[serde(rename = "mean", skip_serializing_if = "Option::is_none")]
    pub mean: Option<i64>,
    /// First traded YES contract price on the market during the candlestick period. May be empty if there was no trade during the period.
    #[serde(rename = "open", skip_serializing_if = "Option::is_none")]
    pub open: Option<i64>,
    /// Last traded YES contract price on the market before the candlestick period. May be empty if there were no trades before the period.
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<i64>,
}

impl PriceDistribution {
    pub fn new() -> PriceDistribution {
        PriceDistribution {
            close: None,
            high: None,
            low: None,
            mean: None,
            open: None,
            previous: None,
        }
    }
}

