/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Schedule {
    /// Scheduled maintenance windows, during which the exchange may be unavailable.
    #[serde(rename = "maintenance_windows")]
    pub maintenance_windows: Vec<models::MaintenanceWindow>,
    #[serde(rename = "standard_hours")]
    pub standard_hours: Box<models::WeeklySchedule>,
}

impl Schedule {
    pub fn new(maintenance_windows: Vec<models::MaintenanceWindow>, standard_hours: models::WeeklySchedule) -> Schedule {
        Schedule {
            maintenance_windows,
            standard_hours: Box::new(standard_hours),
        }
    }
}

