/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SettlementSource : The Name and URL of a settlement source used by Kalshi to determine a market.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettlementSource {
    /// The official name of the settlement source
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The URL of the settlement source
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl SettlementSource {
    /// The Name and URL of a settlement source used by Kalshi to determine a market.
    pub fn new() -> SettlementSource {
        SettlementSource {
            name: None,
            url: None,
        }
    }
}

