/*
 * Kalshi Trade API
 *
 * This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@kalshi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeeklySchedule {
    #[serde(rename = "friday", skip_serializing_if = "Option::is_none")]
    pub friday: Option<Box<models::DailySchedule>>,
    #[serde(rename = "monday", skip_serializing_if = "Option::is_none")]
    pub monday: Option<Box<models::DailySchedule>>,
    #[serde(rename = "saturday", skip_serializing_if = "Option::is_none")]
    pub saturday: Option<Box<models::DailySchedule>>,
    #[serde(rename = "sunday", skip_serializing_if = "Option::is_none")]
    pub sunday: Option<Box<models::DailySchedule>>,
    #[serde(rename = "thursday", skip_serializing_if = "Option::is_none")]
    pub thursday: Option<Box<models::DailySchedule>>,
    #[serde(rename = "tuesday", skip_serializing_if = "Option::is_none")]
    pub tuesday: Option<Box<models::DailySchedule>>,
    #[serde(rename = "wednesday", skip_serializing_if = "Option::is_none")]
    pub wednesday: Option<Box<models::DailySchedule>>,
}

impl WeeklySchedule {
    pub fn new() -> WeeklySchedule {
        WeeklySchedule {
            friday: None,
            monday: None,
            saturday: None,
            sunday: None,
            thursday: None,
            tuesday: None,
            wednesday: None,
        }
    }
}

